# Generated by Django 4.1.1 on 2022-09-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BUYER', ' Buyer'), ('SELLER', 'Seller')], default=None, max_length=10, null=True)),
            ],
        ),
    ]
