# Generated by Django 4.0.5 on 2022-09-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
