# Generated by Django 4.0.5 on 2022-09-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0003_vendor_object_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Tag',
        ),
    ]
