# Generated by Django 4.1.1 on 2022-09-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_usertype_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
